source 'https://cdn.cocoapods.org'
platform :ios, '11.0'

target 'iosApp' do
  use_frameworks!
  pod 'test', :path => '../test'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force CocoaPods targets to always build for x86_64
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end
