# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'multiplatform_compose', :path => '../multiplatform-compose'
  pod 'test', :path => '../test'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAppUITests' do
    # Pods for testing
  end

end

# See https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod/51416359#51416359
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      # Force CocoaPods targets to always build for x86_64
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end

